<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Guneets-MacBook-Air.local" ignored="0" name="testTest" tests="3" failures="2" timestamp="2019-09-02T09:39:24 IST" time="10.285" errors="0">
  <testcase name="TestA" time="10.077" classname="com.test.sample.FunctionalSample1"/>
  <testcase name="TestB" time="0.01" classname="com.test.sample.FunctionalSample1">
    <failure type="java.lang.AssertionError" message="expected 3 but got 4 expected [4] but found [2]">
      <![CDATA[java.lang.AssertionError: expected 3 but got 4 expected [4] but found [2]
at com.test.sample.FunctionalSample1.TestB(FunctionalSample1.java:17)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TestB -->
  <testcase name="TestB" time="0.016" classname="com.test.sample.FunctionalSample1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.reporto.ReportoListener.takeScreenShot(ReportoListener.java:241)
at com.reporto.ReportoListener.onTestFailure(ReportoListener.java:232)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- TestB -->
</testsuite> <!-- testTest -->
